### ISSUE TITLE
Gradle 4.8 and Java 17 Compatibility Issue in DonorHub Project

### ISSUE THREAD

**Issue by amnandan9** [amnandan9/DonorHubv1#5]
I'm experiencing a compatibility issue in the DonorHub project due to an outdated Gradle version. The project currently uses Gradle 4.8 alongside Java 17, but Gradle 4.8 doesn't seem to support Java 17, causing build errors.

Has anyone successfully resolved this issue, or can someone suggest the best approach to upgrade Gradle to a compatible version without affecting the project's dependencies and plugins? Also, are there any known issues with third-party plugins that I should be cautious about when updating Gradle?

**Comment by Harsh2504** [comment]
Hi @amnandan9,
I wanted to let you know that I’ve successfully resolved the issue with the outdated Gradle version. I upgraded Gradle to version 7.2, which is fully compatible with Java 17, and I made sure the project builds correctly with the new configuration. I also addressed the NullPointerException caused by the null UserData object in Firebase, which was leading to app crashes. After adding the necessary null checks, the issue was fixed, and the app no longer crashes.

With these fixes in place, I believe the issue is now closed.
